start @DHCP_START@
end @DHCP_END@
interface @WLAN_IFACE@
option subnet @AP_NETMASK@
option router @AP_IP@
option dns @AP_IP@
option lease @DHCP_LEASE@
pidfile @UDHCPD_PID_FILE@
lease_file @UDHCPD_LEASE_FILE@
